### ISSUE TITLE
Question: Usage

### ISSUE THREAD

**Issue by goodseller** [orlin/gulp-npm-run#2]
I am not pretty get it..

If I have a `npm run editor` script, is the gulp script become as follow and I can run gulp editor? Thanks.

```
'use strict';
var gulp = require('gulp-npm-run')(require('gulp'), {
  exclude: ['editor'], // the test script is excluded
  requireStrict: false,
  npmRun: true // rather than `npm run script` gulp runs the script's value / command(s) 
});

gulp.task('editor', (cb) => {
  // other scripts
});
```

**Comment by orlin** [comment]
Sorry, I've been away from github...  

The `exclude: ['editor']` option means a gulp task will not be added to call the "editor" script from `package.json`, which would be same as $ `npm run editor`.  In your case you don't really need to exclude it, because programatically creating the "editor" task yourself with `gulp.task` would simply add it again.  If an "editor" script / task was imported based on package.json then it would simply be overridden with the `gulp.task` function because because both scripts use the same string key, namely "editor".

I hope this answers your question.

**Comment by goodseller** [comment]
Ic, thanks! You make my day.
